name: Build Docs

on:
  pull_request:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: "3.10"
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          conda install pytorch cpuonly -c pytorch-nightly
          python setup.py sdist bdist_wheel
          pip install dist/*.whl
      - name: Build docs
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          cd docs
          pip install -r requirements.txt
          make html
          touch build/html/.nojekyll
          cd ..
